# Generated by Django 6.0.4 on 2026-05-01 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('doc_type', models.CharField(choices=[('PDF', 'PDF'), ('TXT', 'Text'), ('CSV', 'CSV')], db_index=True, max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_id', 'doc_type'], name='document_do_organiz_d51ccb_idx'), models.Index(fields=['created_at'], name='document_do_created_778a6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('embedding_id', models.CharField(max_length=255, unique=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='document.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_a45e27_idx'), models.Index(fields=['embedding_id'], name='document_ch_embeddi_20c498_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_per_document')],
            },
        ),
    ]
