# Generated by Django 6.0.4 on 2026-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='document_do_organiz_d51ccb_idx',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type'], name='document_do_doc_typ_1e64e1_idx'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='organization_id',
        ),
    ]
