# Generated by Django 6.0.4 on 2026-05-01 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('priority', models.CharField(db_index=True, max_length=50)),
                ('created_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_id', 'status'], name='task_task_organiz_01de3e_idx'), models.Index(fields=['priority'], name='task_task_priorit_21ce1f_idx')],
            },
        ),
    ]
