# Generated by Django 6.0.4 on 2026-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_organiz_01de3e_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_task_status_5e4c6f_idx'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='organization_id',
        ),
    ]
