# Generated by Django 6.0.4 on 2026-05-01 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('query_text', models.TextField()),
                ('rewritten_query', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_id', 'created_at'], name='querie_quer_organiz_6e66d3_idx'), models.Index(fields=['user_id'], name='querie_quer_user_id_7c75d5_idx')],
            },
        ),
    ]
