# Generated by Django 6.0.4 on 2026-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='querylog',
            name='querie_quer_organiz_6e66d3_idx',
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['created_at'], name='querie_quer_created_bd625d_idx'),
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='organization_id',
        ),
    ]
